# 예외처리, 객체관리 종합

## 예외처리(Exception Handling)

### 에러와 예외(Error / Exception)

- 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우
- **Error**
    - 메모리 부족, stack overflow와 같이 일단 발생하면 복구할 수 없는 상황
    - 프로그램의 비정상적 종료를 막을 수 없음 → 디버깅 필요
    - 프로그래밍을 통해서 대처가 가능한가? 그럴 필요가 있는가? 프로그래머의 관심사인가?
    - An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch.
- **Exception**
    - 읽으려는 파일이 없거나, 네트워크 연결이 안되는 등 수습될 수 있는 비교적 상태가 약한 것들
    - 프로그램 코드에 의해 수습될 수 있는 상황
    - 코드를 통해서 프로그램의 비정상적 종료를 막을 수 있는가?
    - An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program’s instructions.
    

### 예외처리(Exception Handling)

- 예외 발생시 프로그램의 비정상 종료를 막고 정상적인 실행 상태를 유지하는 것
- 예외의 감지 및 예외 발생시 동작할 코드 작성 필요
- 왜 필요한가?
    1. 주된 관심사와 보조 관심사를 분리함
        - 메소드의 본래 기능에 집중하고자 함
        - 예외는 사용자가 알아서 처리하도록 넘김
    2. 미리 발생할 수 있는 문제점을 알려주는 효과
        - 메소드에 throws → 발생할 수 있는 예외 명시
    3. 메소드를 잘못 사용하는 것을 방지
        - (ex) `Integer.parseInt("문자열")` → 정수
        - 실수로 `"문자열"` 에 `"ssafy"` 같은 걸 넣었을 때…

### 예외 클래스의 계층

- 예외도 객체구나!

[https://t1.daumcdn.net/cfile/tistory/21476F3E577E91080E](https://t1.daumcdn.net/cfile/tistory/21476F3E577E91080E)

- **Checked Exception**
    - 예외에 대한 대처 코드가 없으면 컴파일이 진행되지 않음 (강제)
        - `try ~catch` (처리) , `throws` 위임(전가)
    - Exception 클래스 상속 (RuntimeException (X))
- **Unchecked Exception** (RuntimeException의 하위클래스)
    - 예외에 대한 대처 코드가 없더라도 컴파일은 진행됨
    - RuntimeException 클래스 상속

### 예외의 발생

```java
public static void main(String[] args){
	int[] nums = {10};
	System.out.println(nums[2]);
}

// Exception in thread "main"
// java.lang.ArrayIndexOutOfBoundsException: 2
```

### 예외 처리 키워드

- 직접 처리 (보통 예외 객체가 발생하는 메소드를 호출하는 쪽이 함)
    - `try`
    - `catch`
    - `finally`
- 간접 처리 (전가)
    - `throws`
- (사용자 정의) 예외 발생시킬 때
    - `throws`
    

### `try ~ catch` 구문

```java
try{
	// 예외가 발생할 수 있는 코드
} catch (Exception e){
	// 예외가 발생했을 때 처리할 코드
}
```

- try 블록에서 예외가 발생하면
- JVM이 해당 Exception 클래스의 객체 생성 후 던짐(throw): `throw new XXException()`
- 던져진 exception을 처리할 수 있는 catch블록에서 받은 후 처리(적당한 catch 블록을 만나지 못하면 예외처리는 실패)
- 정상적으로 처리되면 try-catch 블록을 벗어나 다음 문장 진행
- try 블록에서 어떠한 예외도 발생하지 않는 경우
- catch문을 거치지 않고 try-catch 블록의 다음 흐름 문장을 실행

### 다중 exception handling

- try 블록에서 여러 종류의 예외가 발생할 경우
- 하나의 try블록에 여러 개의 catch블록 추가 가능(예외 종류별로 catch블록 구성)

```java
try{
	// exception이 발생할 만한 코드
} catch (XXException e){
	// XXException 발생시 처리 코드
} catch (YYException e){
	// YYException 발생시 처리 코드
} catch (Exception e){
	// Exception 발생시 처리 코드
}
```

```java
try{
	// exception이 발생할 만한 코드
} catch (Exception e){
	// Exception 발생시 처리 코드
} catch (XXException e){
	// XXException 발생시 처리 코드
} catch (YYException e){
	// YYException 발생시 처리 코드
}
// 뒤 XXException YYException은 있으나 마나
```

- 다중 catch 문장 작성 순서 유의 사항
    - JVM이 던진 예외는 catch 문장을 찾을 때는 다형성이 적용됨
    - 상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음
    - 상속 관계가 없는 경우는 무관
    - 상속 관계에서는 작은 범위(자식)에서 큰 범위(조상)순으로 정의
    

### `try ~ catch ~ finally` 구문을 이용한 예외 처리

- finally는 예외 발생 여부와 상관 없이 언제나 실행
- 중간에 `return` 을 만나는 경우도 finally 블록을 먼저 수행 후 return 실행

```java
try {
 // exception이 발생할 만한 코드 - System 자원 사용
} catch(Exception e){
 // XXException 발생시 처리 코드
} finally{
 // try block에서 접근했던 System 자원의 안전한 원상복구
}

```

### throws 키워드를 통한 처리 위임

- method에서 처리해야 할 하나 이상의 예외를 호출한 곳으로 전달(처리 위임)
- 예외가 없어지는 것이 아니라 단순히 전달됨
- 예외를 전달받은 메소드는 다시 예외 처리의 책임 발생

```java
void exceptionMethod() throws Exception1, Exception2 .. {
	// 예외 발생 코드
}
void methodCaller(){
	try{
		exceptionMethod();
	} catch(Exception e){}
}
```

- 처리하려는 예외의 조상 타입으로 throws 처리 가능